name: taskline
version: '0.7.0'
summary: Tasks, boards & notes for the command-line habitat
description: |
  By utilizing a simple and minimal usage syntax, that requires a flat learning curve, Taskline enables you
  to effectively manage your tasks and notes across multiple boards from within your terminal. All data are
  written atomically to the storage in order to prevent corruptions. At the moment there are two storage modules.
  Local storage where your task and are never shared with anyone or anything, or the firestore module, where your
  tasks are saved in your firestore database and can be shared across all your devices.
  Deleted items are automatically archived and can be inspected or restored at any moment.

  Important!

  To bind taskline to the alias tl use following command 'snap alias taskline tl'

  Highlighted Features

  * Organize tasks & notes to boards
  * Board & timeline views
  * Priority & favorite mechanisms
  * Advanced duedate mechanism
  * Search & filter items
  * Archive & restore deleted items
  * Multiple storage modules.
  * Save date on your local machine at `~/.taskline/storage` or
  * Use the firestore module to sync your tasks across all your devices.
  * Lightweight & fast
  * Data written atomically to storage
  * Custom storage location
  * Progress overview
  * Simple & minimal usage syntax
  * Update notifications
  * Configurable through `~/.taskline.json`

  More informations under https://github.com/perryrh0dan/taskline.

grade: stable
confinement: strict

architectures:
  - amd64
  - i386
  - armhf

apps:
  taskline:
    command: tl
    plugs:
      - home
      - network
      - network-control
      - x11

parts:
  taskline:
    plugin: nodejs
    node-engine: 10.15.0
    node-package-manager: yarn
    source: .
